#!/bin/bash
#Set volume to a specified value or mute/unmute it

if [ "$1" == "mute" ] || [ "$1" == "on" ] || [ "$1" == "off" ] || [ "$1" == "unmute" ]
then
	amixer -D pulse sset Master $1 | grep 'Front Left:' | awk '{print $6}' | tr -d '[]'
else
	amixer -D pulse sset Master $1 | grep 'Front Left:' | awk '{print $5}' | tr -d '[]'
fi
